#!/bin/bash


# SCRIPT TEM COMO FINALIDADE MONITORAR A ATIVIDADE DE ALGUM SERVIÇO SELECIONADO PELO USUÁRIO.

## A SAÍDA DA VERIFICAÇÃO SERÁ ARMAZENADA EM UMA PASTA NO /home/"Nome do usuário"/"NomeDoServico"log,
## O ARQUIVO SERA NOMEADO COM A DATA A QUAL O SCRIPT FOI EXECUTADO.

#	WRITTEN BY <cdomingues@conecto.com.br> in august 2022
#	By Charlie Augusto


echo
echo "Nome do Serviço: "
read serv
echo
echo "VERIFICACAO ${serv^^}"  ## ^^ deixa texto em maiusculo
echo


inpt=$(ps -ef | grep $serv)
arq=$(date +%F)
creat=$(mkdir /home/$USER/$serv"log"/)


for ((loop=1;loop>0;loop++));do
echo
echo "-------------------------------------------------------------------------------------------"
echo
sleep 1800 
echo -e "Verificacao de numero $loop"
echo 
echo $inpt
echo $inpt >> /home/$USER/$serv"log"/${arq}
done

